mei:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: mei_take_out
    username: root
    password: ytj12988
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: kakaowo
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  aliyun:
    oss:
      access-key-id: LTAI5tBogQygYio2evHGsaBi
      access-key-secret: EElWRyJoFogoomLToETR3PRlOdX0rc
      bucket-name: mei-take-out
      endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: 47.96.76.92
    port: 6379
    database: 9
