mei:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: mei_take_out
    username: root
    password: ytj12988
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: kakaowo
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 用户:
    user-secret-key: kakaowo
    # 设置jwt过期时间
    user-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  weChat:
    appid: wx710af829091fd0cd
    secret: 68a59f65a1d0ba794d559c38b7afaba8
    weiChatUrl: https://api.weixin.qq.com/sns/jscode2session
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: http://20f538cc.r2.cpolar.top/notify/paySucess
    refundNotifyUrl: http://20f538cc.r2.cpolar.top/refundSuccess
  aliyun:
    oss:
      access-key-id: LTAI5tBogQygYio2evHGsaBi
      access-key-secret: EElWRyJoFogoomLToETR3PRlOdX0rc
      bucket-name: mei-take-out
      endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: 47.96.76.92
    port: 6379
    database: 9